add html and css to wallet page
GSG-CF04/Financy_App01 pull request #35
Opened 2021-10-22 18:25 UTC by muhannaAtalla20

Relates#15 "

2021-10-22 18:28 UTC, abedshamia approved these changes
👍

2021-10-22 19:16 UTC, sara219 requested changes

2021-10-22 19:16 UTC, sara219 commented on wallet/wallet.html
> +    <link rel="stylesheet" href="css/wallet.css">
wrong CSS file path 

```html
   <link rel="stylesheet" href="wallet.css">
```

2021-10-22 19:16 UTC, sara219 commented on wallet/wallet.html
> +        </div>
all the images go with the wrong path, make sure that the entry sequence for files and folders is correct

```html
            <img src="/assets/images/wallet/account-user.png" alt="">

```

2021-10-23 19:29 UTC, farahalzard approved these changes

2021-10-24 10:17 UTC, sara219 approved these changes

2021-10-24 10:20 UTC, merged